### ISSUE TITLE
[QUEST] help using docker

### ISSUE THREAD

**Issue by pallebone** [PugPickles/UnraidCA#9]
Hi there,

I am interested in learning to use this docker as a minecraft server on unraid as a docker but have some questions. 

Can this server somehow be integrated with geyser and/or floodgate to allow crossplay? I dont see a docker for that or how can I do that? Sorry if this is a silly question. 

What happens when mojang release an update? How do clients connect if they are newer than the server?

Is there a forum post on the unraid forum at all regarding this docker?

Thank you.

**Comment by PugPickles** [comment]
Hi, 
Geysir/Floodgate I can't say, I didn't create the image for myself, but if it's plugins (like worldedit) you can just put them in the plugins mount. (Otherwise ask at unraid forum if someone can help with more knowledge about it. Sorry)

For updates you can simply change the server version / build, it will then automatically download and start the appropriate version.
You can change the version/build via these variables: `SRV_VERSION` and `SRV_BUILD`
default is:
* SRV_VERSION=1.19.2
* SRV_BUILD=280

Here you can find newer versions for 1.19 (the build is next to the hashtag)
https://papermc.io/downloads#Paper-1.19

**Comment by pallebone** [comment]
Ok thank you :)
